### ISSUE TITLE
Add Dependabot Config

### ISSUE THREAD

**Issue by rajbos** [copilot-extensions/blackbeard-extension#3]
Running the steps on the readme to install the dependencies shows 5 vulnerabilities in packages. 
If possible, enable Dependabot and keep things up to date (especially on security alerts).

I forked the repo and enabled Dependabot: 
![Image](https://github.com/user-attachments/assets/24d4e164-c2a8-43a9-81fc-c31c7a39d74a)

Letting Dependabot fix all the errors with PR's and the alerts are fixed. 

Either add Dependabot (best option IMO), or I can create a PR with the version updates: [compare my fork](https://github.com/copilot-extensions/blackbeard-extension/compare/main...rajbos:blackbeard-extension:main).

**Comment by Houndie** [comment]
Thanks for the note!

We've enabled dependabot on this side and we will hopefully have these issues fixed soon.
