### ISSUE TITLE
Personal Access Tokens are not supported for this endpoint

### ISSUE THREAD

**Issue by franzcmarcelo** [copilot-extensions/blackbeard-extension#6]
### Environment
- Node.js version: v22.9.0
- Operating System: Windows 10

### Error
I have tried both classic and fine-grained Personal Access Tokens, and both result in the same error.

`bad request: Personal Access Tokens are not supported for this endpoint`

The tokens have the necessary scopes/permissions for accessing the GitHub API.

### Possible Solution
Clarify the type of token required for this endpoint in the documentation.

### References
[Get the authenticated user](https://docs.github.com/es/rest/users/users?apiVersion=2022-11-28#get-the-authenticated-user)

**Comment by Houndie** [comment]
Hi @franzcmarcelo !

You are correct that PATs do not work with copilot API, you'll need to use the token that comes in with the request as demonstrated in the code.
